dubbo:
  application:
    name: product-cent-web
  registry:
    protocol: zookeeper
    address: 192.168.84.128:2181
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.84.128
    username: Java1902
    password: 123
    port: 5672
    virtual-host: Java1902
server:
  port: 9090

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.36.8.8:22122

image:
  server: http://10.36.8.8/
