spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
dubbo:
  application:
    name: register-service
  registry:
    protocol: zookeeper
    address: 192.168.84.128:2181
  protocol:
    port: 28813

server:
  port: 8083
