spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.84.128
    port: 6379
    password: wwn
    jedis:
      pool:
        max-active: 66
dubbo:
  application:
    name: sso-service
  registry:
    protocol: zookeeper
    address: 192.168.84.128:2181
  protocol:
    port: 28814




server:
  port: 8084
